/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uUeNeJpYxbY
 */
import Link from "next/link"

export default function frontend() {
  return (
    <section className="w-full h-screen flex flex-col items-center justify-center bg-gray-100 dark:bg-gray-900 p-4 md:p-6">
      <div className="space-y-6 flex flex-col items-center">
        <img
          className="h-72 w-72 object-contain mb-8"
          height="300"
          src="https://s1.cdn.rahb.ca/rahbca/wp-content/uploads/2023/01/rahb_logo.png"
          style={{
            aspectRatio: "300/300",
            objectFit: "cover",
          }}
          width="300"
        />
        <h1 className="text-4xl font-bold text-center text-gray-800 dark:text-gray-200">
          OpenHouses.ca Has Been Retired
        </h1>
        <p className="text-lg text-center text-gray-600 dark:text-gray-400 max-w-[600px]">
          We regret to inform you that OpenHouses.ca has been retired. The open house information is now available on <strong><a href="#" target="_blank">REALTOR.ca</a></strong>.{"\n"}
        </p>
        <p>
          For your convenience, you will be redirected there shortly. If you are not redirected, please click the button below.
        </p>
        <Link
          className="inline-flex h-12 items-center justify-center rounded-md bg-green-500 px-8 text-lg font-medium text-gray-50 shadow transition-colors hover:bg-green-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-green-500 dark:text-gray-900 dark:hover:bg-green-600 dark:focus-visible:ring-green-700"
          href="#"
        >
          Visit REALTOR.ca
        </Link>
      </div>
      <footer className="mt-auto text-center text-gray-600 dark:text-gray-400 py-4">
        <p>
          © 2024 <a href="#">REALTORS® Association of Hamilton-Burlington</a>. All rights reserved.
          <br />
          The trademarks REALTOR®, REALTORS®, and the REALTOR® logo are controlled by The Canadian Real Estate Association (CREA) and identify real estate professionals who are members of CREA.
        </p>
      </footer>
    </section>
  )
}
